const String getMessages = "GetMessages"; //done
const String getTrainings = "GetTrainings"; //done
const String getPeriodTerms = "GetPeriodTerms"; //done
const String getAddedSubjects = "GetAddedSubjects"; //done
const String setReadedMessage = "SetReadedMessage"; //done
const String getExams = "GetExams";
const String getCalendarData = "GetCalendarData";
const String getSubjects = 'GetSubjects';
const String getCurriculums = 'GetCurriculums';
const String getCourses = 'GetCourses';
