const String getMessages = "GetMessages"; //done
const String getTrainings = "GetTrainings"; //done
const String getPeriodTerms = "GetPeriodTerms"; //done
const String getAddedSubjects = "GetAddedSubjects"; //done
const String setReadedMessage = "SetReadedMessage"; //done
const String getExams = "GetExams"; //done
const String getCalendarData = "GetCalendarData"; //done
const String getSubjects = 'GetSubjects';
const String getCurriculums = 'GetCurriculums'; //done
const String getCourses = 'GetCourses';
const String setNewPassword = 'SetNewPassword'; //done
const String setExamSigning = 'SetExamSigning'; //done